--Historical Religions
UPDATE Civilization_Religions SET ReligionType = 
	( CASE WHEN EXISTS(SELECT Type FROM Religions WHERE Type = 'RELIGION_PROTESTANT_BAPTIST' )
		THEN 'RELIGION_PROTESTANT_BAPTIST'
		ELSE ( CASE WHEN EXISTS(SELECT Type FROM Religions WHERE Type = 'RELIGION_PROTESTANT_METHODISM' )
		THEN 'RELIGION_PROTESTANT_METHODISM'
		ELSE ( CASE WHEN EXISTS(SELECT Type FROM Religions WHERE Type = 'RELIGION_PROTESTANTISM' )
		THEN 'RELIGION_PROTESTANTISM'
		ELSE 'RELIGION_CHRISTIANITY' END ) END ) END
	) WHERE CivilizationType = 'CIVILIZATION_TEXAS';

CREATE TRIGGER ReligionTexasSupportBaptist
AFTER INSERT ON Religions WHEN 'RELIGION_PROTESTANT_BAPTIST' = NEW.Type
BEGIN
	UPDATE Civilization_Religions 
	SET ReligionType = 'RELIGION_PROTESTANT_BAPTIST'
	WHERE CivilizationType IN ('CIVILIZATION_TEXAS');
END;

CREATE TRIGGER ReligionTexasSupportMethodism
AFTER INSERT ON Religions WHEN 'RELIGION_PROTESTANT_METHODISM' = NEW.Type
BEGIN
	UPDATE Civilization_Religions SET ReligionType = 
		( CASE WHEN EXISTS(SELECT Type FROM Religions WHERE Type = 'RELIGION_PROTESTANT_BAPTIST' )
			THEN 'RELIGION_PROTESTANT_BAPTIST'
			ELSE 'RELIGION_PROTESTANT_METHODISM' END 
		) WHERE CivilizationType = 'CIVILIZATION_TEXAS';
END;