-----------------------------------------------------------------------------
-- Reduced Unit Graphics
-- Alternate Settlers for use with R.E.D. Modpack
-----------------------------------------------------------------------------

--Africa:
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_SONGHAI';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_SONGHAI','ART_DEF_UNIT_MEMBER_AFRIMALE1',"1");		--default
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_SONGHAI','ART_DEF_UNIT_MEMBER_AFRICAMEL',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_ETHIOPIA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_ETHIOPIA','ART_DEF_UNIT_MEMBER_AFRIMALE1',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_ETHIOPIA','ART_DEF_UNIT_MEMBER_AFRICAMEL',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_ZULU';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_ZULU','ART_DEF_UNIT_MEMBER_AFRIMALE1',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_ZULU','ART_DEF_UNIT_MEMBER_AFRICAMEL',"1");

--Americas:
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_AZTEC';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_AZTEC','ART_DEF_UNIT_MEMBER_AMERMALE1',"1");		--default
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_AZTEC','ART_DEF_UNIT_MEMBER_AMERLLAMA',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_MAYA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_MAYA','ART_DEF_UNIT_MEMBER_AMERMALE1',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_MAYA','ART_DEF_UNIT_MEMBER_AMERLLAMA',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_SHOSHONE';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_SHOSHONE','ART_DEF_UNIT_MEMBER_AMERMALE2',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_SHOSHONE','ART_DEF_UNIT_MEMBER_AMERLLAMA',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_IROQUOIS';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_IROQUOIS','ART_DEF_UNIT_MEMBER_AMERMALE4',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_IROQUOIS','ART_DEF_UNIT_MEMBER_AMERLLAMA',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_INCA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_INCA','ART_DEF_UNIT_MEMBER_AMERMALE4',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_INCA','ART_DEF_UNIT_MEMBER_AMERLLAMA',"1");

--Asia:
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_INDIA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_INDIA','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_M1',"1");	--default
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_INDIA','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_OX',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_INDONESIA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_INDONESIA','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_M1',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_INDONESIA','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_OX',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_POLYNESIA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_POLYNESIA','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_M1',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_POLYNESIA','ART_DEF_UNIT_MEMBER_EURODONKEY',"1");		-- donkey

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_MONGOL';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_MONGOL','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_M2',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_MONGOL','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_OX',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_HUNS';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_HUNS','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_M2',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_HUNS','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_OX',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_JAPAN';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_JAPAN','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_M3',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_JAPAN','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_OX',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_KOREA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_KOREA','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_M3',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_KOREA','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_OX',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_CHINA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_CHINA','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_M4',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_CHINA','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_OX',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_SIAM';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_SIAM','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_M4',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_SIAM','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_OX',"1");

--Europe:
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_AMERICA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_AMERICA','ART_DEF_UNIT_MEMBER_EUROMALE20',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_AMERICA','ART_DEF_UNIT_MEMBER_EURODONKEY',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_ENGLAND';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_ENGLAND','ART_DEF_UNIT_MEMBER_EUROMALE20',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_ENGLAND','ART_DEF_UNIT_MEMBER_EURODONKEY',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_DENMARK';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_DENMARK','ART_DEF_UNIT_MEMBER_EUROMALE20',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_DENMARK','ART_DEF_UNIT_MEMBER_EURODONKEY',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_AUSTRIA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_AUSTRIA','ART_DEF_UNIT_MEMBER_EUROMALE20',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_AUSTRIA','ART_DEF_UNIT_MEMBER_EURODONKEY',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_NETHERLANDS';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_NETHERLANDS','ART_DEF_UNIT_MEMBER_EUROMALE20',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_NETHERLANDS','ART_DEF_UNIT_MEMBER_EURODONKEY',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_CELTS';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_CELTS','ART_DEF_UNIT_MEMBER_EUROMALE20',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_CELTS','ART_DEF_UNIT_MEMBER_EURODONKEY',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_SWEDEN';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_SWEDEN','ART_DEF_UNIT_MEMBER_EUROMALE20',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_SWEDEN','ART_DEF_UNIT_MEMBER_EURODONKEY',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_BRAZIL';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_BRAZIL','ART_DEF_UNIT_MEMBER_EUROMALE25',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_BRAZIL','ART_DEF_UNIT_MEMBER_EURODONKEY',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_PORTUGAL';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_PORTUGAL','ART_DEF_UNIT_MEMBER_EUROMALE25',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_PORTUGAL','ART_DEF_UNIT_MEMBER_EURODONKEY',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_SPAIN';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_SPAIN','ART_DEF_UNIT_MEMBER_EUROMALE25',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_SPAIN','ART_DEF_UNIT_MEMBER_EURODONKEY',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_FRANCE';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_FRANCE','ART_DEF_UNIT_MEMBER_EUROMALE35',"1");			--default
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_FRANCE','ART_DEF_UNIT_MEMBER_EURODONKEY',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_GERMANY';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_GERMANY','ART_DEF_UNIT_MEMBER_EUROMALE35',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_GERMANY','ART_DEF_UNIT_MEMBER_EURODONKEY',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_POLAND';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_POLAND','ART_DEF_UNIT_MEMBER_EUROMALE35',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_POLAND','ART_DEF_UNIT_MEMBER_EURODONKEY',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_RUSSIA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_RUSSIA','ART_DEF_UNIT_MEMBER_EUROMALE35',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_RUSSIA','ART_DEF_UNIT_MEMBER_EURODONKEY',"1");

--Mediterranean:
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_BYZANTIUM';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_BYZANTIUM','ART_DEF_UNIT_MEMBER_EUROMALE35',"1");		--default
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_BYZANTIUM','ART_DEF_UNIT_MEMBER_EURODONKEY',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_GREECE';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_GREECE','ART_DEF_UNIT_MEMBER_EUROMALE35',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_GREECE','ART_DEF_UNIT_MEMBER_EURODONKEY',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_ROME';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_ROME','ART_DEF_UNIT_MEMBER_EUROMALE35',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_ROME','ART_DEF_UNIT_MEMBER_EURODONKEY',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_VENICE'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_VENICE','ART_DEF_UNIT_MEMBER_EUROMALE35',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_BABYLON';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_BABYLON','ART_DEF_UNIT_MEMBER_AFRIMALE2',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_BABYLON','ART_DEF_UNIT_MEMBER_AFRICAMEL',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_CARTHAGE';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_CARTHAGE','ART_DEF_UNIT_MEMBER_AFRIMALE2',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_CARTHAGE','ART_DEF_UNIT_MEMBER_AFRICAMEL',"1");

--Middle East:
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_ARABIA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_ARABIA','ART_DEF_UNIT_MEMBER_AFRIMALE2',"1");			--default
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_ARABIA','ART_DEF_UNIT_MEMBER_AFRICAMEL',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_ASSYRIA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_ASSYRIA','ART_DEF_UNIT_MEMBER_AFRIMALE2',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_ASSYRIA','ART_DEF_UNIT_MEMBER_AFRICAMEL',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_EGYPT';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_EGYPT','ART_DEF_UNIT_MEMBER_AFRIMALE2',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_EGYPT','ART_DEF_UNIT_MEMBER_AFRICAMEL',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_MOROCCO';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_MOROCCO','ART_DEF_UNIT_MEMBER_AFRIMALE2',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_MOROCCO','ART_DEF_UNIT_MEMBER_AFRICAMEL',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_OTTOMAN';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_OTTOMAN','ART_DEF_UNIT_MEMBER_AFRIMALE2',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_OTTOMAN','ART_DEF_UNIT_MEMBER_AFRICAMEL',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_PERSIA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_PERSIA','ART_DEF_UNIT_MEMBER_AFRIMALE2',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_PERSIA','ART_DEF_UNIT_MEMBER_AFRICAMEL',"1");