-- Adapted by calcul8or from a file by JFD

INSERT INTO GreatWorks 
			(Type, 										GreatWorkClassType,			Description,									Quote,													Audio,								Image)
VALUES		
			('GREAT_WORK_FREEDOM_OF_SPEECH', 			'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_FREEDOM_OF_SPEECH',			'TXT_KEY_GREAT_WORK_QUOTE_FREEDOM_OF_SPEECH',			'AS2D_DISCIPLE_ARTIST_WRITER',		'GreatWriter_Background.dds'),
			('GREAT_WORK_CHARACTER_OF_HONEST_MAN', 		'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_CHARACTER_OF_HONEST_MAN',	'TXT_KEY_GREAT_WORK_QUOTE_CHARACTER_OF_HONEST_MAN',		'AS2D_DISCIPLE_ARTIST_WRITER',		'GreatWriter_Background.dds'),
			('GREAT_WORK_THE_HARDER',					'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_THE_HARDER',				'TXT_KEY_GREAT_WORK_QUOTE_THE_HARDER',					'AS2D_DISCIPLE_ARTIST_WRITER',		'GreatWriter_Background.dds'),
			('GREAT_WORK_NO_EXCUSE',					'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_NO_EXCUSE',					'TXT_KEY_GREAT_WORK_QUOTE_NO_EXCUSE',					'AS2D_DISCIPLE_ARTIST_WRITER',		'GreatWriter_Background.dds');

			--('GREAT_WORK_THE_LETTERS_OF_SAINT_CATHERINE_OF_SIENA', 			'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_THE_LETTERS_OF_SAINT_CATHERINE_OF_SIENA',		'TXT_KEY_GREAT_WORK_QUOTE_THE_LETTERS_OF_SAINT_CATHERINE_OF_SIENAE',		'AS2D_DISCIPLE_ARTIST_WRITER',										'GreatWriter_Background.dds'),
			--('GREAT_WORK_THE_DIVINE_COMEDY', 								'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_THE_DIVINE_COMEDY',								'TXT_KEY_GREAT_WORK_QUOTE_HE_DIVINE_COMEDY',								'AS2D_DISCIPLE_ARTIST_WRITER',										'GreatWriter_Background.dds'),
			--('GREAT_WORK_THE_BETHROTHED', 									'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_THE_BETHROTHED',								'TXT_KEY_GREAT_WORK_QUOTE_THE_BETHROTHED',									'AS2D_DISCIPLE_ARTIST_WRITER',										'GreatWriter_Background.dds'),
			--('GREAT_WORK_THE_LIFE_OF_SAINT_TERESA_OF_AVILA_BY_HERSELF', 	'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_THE_LIFE_OF_SAINT_TERESA_OF_AVILA_BY_HERSELF',	'TXT_KEY_GREAT_WORK_QUOTE_THE_LIFE_OF_SAINT_TERESA_OF_AVILA_BY_HERSELF',	'AS2D_DISCIPLE_ARTIST_WRITER',										'GreatWriter_Background.dds'),
			--('GREAT_WORK_INTRODUCTION_TO_THE_DEVOUT_LIFE', 					'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_INTRODUCTION_TO_THE_DEVOUT_LIFE',				'TXT_KEY_GREAT_WORK_QUOTE_INTRODUCTION_TO_THE_DEVOUT_LIFE',					'AS2D_DISCIPLE_ARTIST_WRITER',										'GreatWriter_Background.dds'),
			--('GREAT_WORK_ASCENT_OF_MOUNT_CARMEL', 							'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_ASCENT_OF_MOUNT_CARMEL',						'TXT_KEY_GREAT_WORK_QUOTE_ASCENT_OF_MOUNT_CARMEL',							'AS2D_DISCIPLE_ARTIST_WRITER',										'GreatWriter_Background.dds'),
			--('GREAT_WORK_DIES_IRAE', 										'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_DIES_IRAE',										'TXT_KEY_GREAT_WORK_QUOTE_DIES_IRAE',										'AS2D_DISCIPLE_ARTIST_WRITER',										'GreatWriter_Background.dds'),
			--('GREAT_WORK_SUMMA_THEOLOGICA', 								'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_SUMMA_THEOLOGICA',								'TXT_KEY_GREAT_WORK_QUOTE_SUMMA_THEOLOGICA',								'AS2D_DISCIPLE_ARTIST_WRITER',										'GreatWriter_Background.dds'),
			--('GREAT_WORK_STORY_OF_A_SOUL', 									'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_STORY_OF_A_SOUL',								'TXT_KEY_GREAT_WORK_QUOTE_STORY_OF_A_SOUL',									'AS2D_DISCIPLE_ARTIST_WRITER',										'GreatWriter_Background.dds'),
			--('GREAT_WORK_THE_BOOK_OF_PASTORAL_RULE', 						'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_THE_BOOK_OF_PASTORAL_RULE',						'TXT_KEY_GREAT_WORK_QUOTE_THE_BOOK_OF_PASTORAL_RULE',						'AS2D_DISCIPLE_ARTIST_WRITER',										'GreatWriter_Background.dds'),
			--('GREAT_WORK_CITY_OF_GOD', 										'GREAT_WORK_LITERATURE',	'TXT_KEY_GREAT_WORK_CITY_OF_GOD',									'TXT_KEY_GREAT_WORK_QUOTE_CITY_OF_GOD',										'AS2D_DISCIPLE_ARTIST_WRITER',										'GreatWriter_Background.dds');
--==========================================================================================================================		
--==========================================================================================================================	

INSERT INTO Unit_UniqueNames
			(UnitType,				UniqueName,							GreatWorkType)
VALUES		
			('UNIT_VAPOLITICIAN',	'TXT_KEY_GREAT_PERSON_WASHINGTON2',	'GREAT_WORK_FREEDOM_OF_SPEECH'),
			('UNIT_VAPOLITICIAN',	'TXT_KEY_GREAT_PERSON_WASHINGTON3',	'GREAT_WORK_CHARACTER_OF_HONEST_MAN'),
			('UNIT_VAPOLITICIAN',	'TXT_KEY_GREAT_PERSON_WASHINGTON4',	'GREAT_WORK_THE_HARDER'),
			('UNIT_VAPOLITICIAN',	'TXT_KEY_GREAT_PERSON_WASHINGTON1',	'GREAT_WORK_NO_EXCUSE');

