-----------------------------------------------------------------------------
-- Reduced Unit Graphics
-- Base Units
-----------------------------------------------------------------------------

-- SOLDIERS (0.18)
------------------------------------------------
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type IN (SELECT UnitMemberInfoType FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType IN
	(SELECT UnitArtInfo FROM Units WHERE MoveRate = 'BIPED'));
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type IN (SELECT UnitMemberInfoType FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType IN
	(SELECT UnitArtInfo FROM Units WHERE MoveRate = 'HEAVY_BIPED'));

-- ARCHER				
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_ARCHER%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_ARCHER%';
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType = 'ART_DEF_UNIT_ARCHER';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_ARCHER','ART_DEF_UNIT_MEMBER_ARCHER_V2',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_ARCHER','ART_DEF_UNIT_MEMBER_ARCHER',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_ARCHER','ART_DEF_UNIT_MEMBER_ARCHER_V3',"1");
UPDATE ArtDefine_UnitInfos SET Formation = 'Archer' WHERE Type LIKE 'ART_DEF_UNIT_ARCHER%';
-- BABYLONIAN BOWMAN
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_BABYLONIAN_BOWMAN';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_BABYLONIAN_BOWMAN';
UPDATE ArtDefine_UnitInfos SET Formation = 'Archer' WHERE Type = 'ART_DEF_UNIT_U_BABYLONIAN_BOWMAN';
-- BARBARIAN ARCHER
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_BARBARIAN_ARCHER%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_BARBARIAN_ARCHER_01';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_BARBARIAN_ARCHER_V2';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_BARBARIAN_ARCHER_V3';
UPDATE ArtDefine_UnitInfos SET Formation = 'Barbarian' WHERE Type LIKE 'ART_DEF_UNIT_BARBARIAN_ARCHER%';
-- INCAN SLINGER
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_INCAN_SLINGER';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_INCAN_SLINGER';
UPDATE ArtDefine_UnitInfos SET Formation = 'Archer' WHERE Type = 'ART_DEF_UNIT_U_INCAN_SLINGER';
-- MAYAN ATLALIST
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_MAYAN_ATLALIST';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_MAYAN_ATLALIST';
UPDATE ArtDefine_UnitInfos SET Formation = 'Archer' WHERE Type = 'ART_DEF_UNIT_U_MAYAN_ATLALIST';

-- MUSKETMAN
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_MUSKETMAN%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_MUSKETMAN%';
UPDATE ArtDefine_UnitInfos SET Formation = 'HonorableGunpowder' WHERE Type LIKE 'ART_DEF_UNIT_MUSKETMAN%';
-- AMERICAN MINUTEMAN
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_AMERICAN_MINUTEMAN';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_AMERICAN_MINUTEMAN';
UPDATE ArtDefine_UnitInfos SET Formation = 'HonorableGunpowder' WHERE Type = 'ART_DEF_UNIT_U_AMERICAN_MINUTEMAN';
-- FRENCH MUSKETEER
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_FRENCH_MUSKETEER';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_FRENCH_MUSKETEER';
UPDATE ArtDefine_UnitInfos SET Formation = 'HonorableGunpowder' WHERE Type = 'ART_DEF_UNIT_U_FRENCH_MUSKETEER';
-- OTTOMAN JANISSARY
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_OTTOMAN_JANISSARY';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_OTTOMAN_JANISSARY';
UPDATE ArtDefine_UnitInfos SET Formation = 'HonorableGunpowder' WHERE Type = 'ART_DEF_UNIT_U_OTTOMAN_JANISSARY';
-- SPANISH TERCIO
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_SPANISH_TERCIO_ARCABUCERO';
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_SPANISH_TERCIO_PIQUERO';
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType = 'ART_DEF_UNIT_U_SPANISH_TERCIO';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_U_SPANISH_TERCIO','ART_DEF_UNIT_MEMBER_U_SPANISH_TERCIO_PIQUERO',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_U_SPANISH_TERCIO','ART_DEF_UNIT_MEMBER_U_SPANISH_TERCIO_ARCABUCERO',"2");
UPDATE ArtDefine_UnitInfos SET Formation = 'OffsetPikeman' WHERE Type = 'ART_DEF_UNIT_U_SPANISH_TERCIO';

-- PIKEMAN
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_PIKEMAN%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_PIKEMAN%';
UPDATE ArtDefine_UnitInfos SET Formation = 'Pikeman' WHERE Type LIKE 'ART_DEF_UNIT_PIKEMAN%';
-- GERMAN LANDSKNECHT
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_GERMAN_LANDSKNECHT_A';
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_GERMAN_LANDSKNECHT_B';
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType = 'ART_DEF_UNIT_U_GERMAN_LANDSKNECHT';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_U_GERMAN_LANDSKNECHT','ART_DEF_UNIT_MEMBER_U_GERMAN_LANDSKNECHT_A',"2");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_U_GERMAN_LANDSKNECHT','ART_DEF_UNIT_MEMBER_U_GERMAN_LANDSKNECHT_B',"1");
UPDATE ArtDefine_UnitInfos SET Formation = 'Pikeman' WHERE Type = 'ART_DEF_UNIT_U_GERMAN_LANDSKNECHT';
-- ZULU IMPI WARRIOR
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_U_ZULU_IMPI_WARRIOR%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_ZULU_IMPI_WARRIOR';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_ZULU_IMPI_WARRIOR_V2';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_ZULU_IMPI_WARRIOR_V3';
UPDATE ArtDefine_UnitInfos SET Formation = 'UnFormed' WHERE Type = 'ART_DEF_UNIT_U_ZULU_IMPI_WARRIOR';

-- SPEARMAN
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_SPEARMAN%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_SPEARMAN%';
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType = 'ART_DEF_UNIT_SPEARMAN';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_SPEARMAN','ART_DEF_UNIT_MEMBER_SPEARMAN_V2',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_SPEARMAN','ART_DEF_UNIT_MEMBER_SPEARMAN',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_SPEARMAN','ART_DEF_UNIT_MEMBER_SPEARMAN_V3',"1");
UPDATE ArtDefine_UnitInfos SET Formation = 'Phalanx' WHERE Type LIKE 'ART_DEF_UNIT_SPEARMAN%';
-- BARBARIAN SPEARMAN
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_BARBARIAN_SPEARMAN%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_BARBARIAN_SPEARMAN';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_BARBARIAN_SPEARMAN_V2';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_BARBARIAN_SPEARMAN_V3';
UPDATE ArtDefine_UnitInfos SET Formation = 'Barbarian' WHERE Type LIKE 'ART_DEF_UNIT_BARBARIAN_SPEARMAN%';
-- CELT PICTISH WARRIOR
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_CELT_PICTISH_WARRIOR';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_CELT_PICTISH_WARRIOR';
UPDATE ArtDefine_UnitInfos SET Formation = 'UnFormed' WHERE Type = 'ART_DEF_UNIT_U_CELT_PICTISH_WARRIOR';
-- GREEK HOPLITE
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_GREEK_HOPLITE';
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType = 'ART_DEF_UNIT_U_GREEK_HOPLITE';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_U_GREEK_HOPLITE','ART_DEF_UNIT_MEMBER_U_GREEK_HOPLITE',"3");
UPDATE ArtDefine_UnitInfos SET Formation = 'Phalanx' WHERE Type = 'ART_DEF_UNIT_U_GREEK_HOPLITE';
-- PERSIAN IMMORTAL
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_PERSIAN_IMMORTAL';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_PERSIAN_IMMORTAL';
UPDATE ArtDefine_UnitInfos SET Formation = 'Phalanx' WHERE Type = 'ART_DEF_UNIT_U_PERSIAN_IMMORTAL';
-- SWORDSMAN
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_SWORDSMAN%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_SWORDSMAN%';
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType = 'ART_DEF_UNIT_SWORDSMAN';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_SWORDSMAN','ART_DEF_UNIT_MEMBER_SWORDSMAN_V2',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_SWORDSMAN','ART_DEF_UNIT_MEMBER_SWORDSMAN',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_SWORDSMAN','ART_DEF_UNIT_MEMBER_SWORDSMAN_V3',"1");
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultMelee' WHERE Type LIKE 'ART_DEF_UNIT_SWORDSMAN%';
-- BARBARIAN SWORDSMAN
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_BARBARIAN_SWORDSMAN%';			
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_BARBARIAN_SWORDSMAN';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_BARBARIAN_SWORDSMAN_V2';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_BARBARIAN_SWORDSMAN_V3';
UPDATE ArtDefine_UnitInfos SET Formation = 'Barbarian' WHERE Type LIKE 'ART_DEF_UNIT_BARBARIAN_SWORDSMAN%';
-- GADRAUHTS SWORDSMAN
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_GADRAUHTS_SWORDSMAN';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_GADRAUHTS_SWORDSMAN';
UPDATE ArtDefine_UnitInfos SET Formation = 'UnFormed' WHERE Type = 'ART_DEF_UNIT_GADRAUHTS_SWORDSMAN';
-- INDONESIAN KRIS SWORDSMAN
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_INDONESIAN_KRIS_SWORDSMAN';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_INDONESIAN_KRIS_SWORDSMAN';
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultMelee' WHERE Type = 'ART_DEF_UNIT_U_INDONESIAN_KRIS_SWORDSMAN';
-- IROQUOIAN MOHAWK WARRIOR
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_IROQUOIAN_MOHAWKWARRIOR';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_IROQUOIAN_MOHAWKWARRIOR';
UPDATE ArtDefine_UnitInfos SET Formation = 'UnFormed' WHERE Type = 'ART_DEF_UNIT_U_IROQUOIAN_MOHAWKWARRIOR';
-- ROMAN LEGION
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_ROMAN_LEGION';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_ROMAN_LEGION';
UPDATE ArtDefine_UnitInfos SET Formation = 'Phalanx' WHERE Type = 'ART_DEF_UNIT_U_ROMAN_LEGION';

-- WARRIOR
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_WARRIOR%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_WARRIOR%';
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType = 'ART_DEF_UNIT__WARRIOR';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__WARRIOR','ART_DEF_UNIT_MEMBER_WARRIOR_V2',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__WARRIOR','ART_DEF_UNIT_MEMBER_WARRIOR',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__WARRIOR','ART_DEF_UNIT_MEMBER_WARRIOR_V4',"1");
UPDATE ArtDefine_UnitInfos SET Formation = 'Warrior' WHERE Type LIKE 'ART_DEF_UNIT__WARRIOR%';
-- BARBARIAN WARRIOR
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_BARBARIAN_EURO%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_BARBARIAN_EURO_ALPHA';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_BARBARIAN_EURO_BRAVO';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_BARBARIAN_EURO_CHARLIE';
UPDATE ArtDefine_UnitInfos SET Formation = 'Barbarian' WHERE Type LIKE 'ART_DEF_UNIT_BARBARIAN_EURO%';
-- AZTEC JAGUAR
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_AZTEC_JAGUAR';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_AZTEC_JAGUAR';
UPDATE ArtDefine_UnitInfos SET Formation = 'UnFormed' WHERE Type = 'ART_DEF_UNIT_U_AZTEC_JAGUAR';
-- POLYNESIAN MAORI WARRIOR
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.17 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_POLYNESIAN_MAORI_WARRIOR';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_POLYNESIAN_MAORI_WARRIOR';
UPDATE ArtDefine_UnitInfos SET Formation = 'UnFormed' WHERE Type = 'ART_DEF_UNIT_U_POLYNESIAN_MAORI_WARRIOR';

-- others
-- COMPOSITE BOWMAN
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_COMPOSITE_BOWMAN%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_COMPOSITE_BOWMAN%';
UPDATE ArtDefine_UnitInfos SET Formation = 'Archer' WHERE Type LIKE 'ART_DEF_UNIT_COMPOSITE_BOWMAN%';
-- CROSSBOWMAN
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_CROSSBOWMAN%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_CROSSBOWMAN%';
UPDATE ArtDefine_UnitInfos SET Formation = 'Archer' WHERE Type LIKE 'ART_DEF_UNIT_CROSSBOWMAN%';
-- CHINESE CHU-KO-NU				
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_CHINESE_CHUKONU';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_CHINESE_CHUKONU';
UPDATE ArtDefine_UnitInfos SET Formation = 'Archer' WHERE Type = 'ART_DEF_UNIT_U_CHINESE_CHUKONU';
-- ENGLISH LONGBOWMAN
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_ENGLISH_LONGBOWMAN';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_ENGLISH_LONGBOWMAN';
UPDATE ArtDefine_UnitInfos SET Formation = 'Archer' WHERE Type = 'ART_DEF_UNIT_U_ENGLISH_LONGBOWMAN';
-- WW1 INFANTRY
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_WW1_INFANTRY%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_WW1_INFANTRY%';
UPDATE ArtDefine_UnitInfos SET Formation = 'UnFormed' WHERE Type LIKE 'ART_DEF_UNIT_WW1_INFANTRY%';
-- FRENCH FOREIGN LEGION
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_FRENCH_FOREIGNLEGION';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_FRENCH_FOREIGNLEGION';
UPDATE ArtDefine_UnitInfos SET Formation = 'UnFormed' WHERE Type = 'ART_DEF_UNIT_U_FRENCH_FOREIGNLEGION';
-- WW2 INFANTRY (G+K)
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_WW2_INFANTRY%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_WW1_INFANTRY%';
UPDATE ArtDefine_UnitInfos SET Formation = 'UnFormed' WHERE Type LIKE 'ART_DEF_UNIT_WW2_INFANTRY%';
-- INFANTRY
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_INFANTRY%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_INFANTRY%';
UPDATE ArtDefine_UnitInfos SET Formation = 'UnFormed' WHERE Type LIKE 'ART_DEF_UNIT_INFANTRY%';
-- BRAZILIAN PRACINHAS
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_BRAZILIAN_PRACINHAS';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_BRAZILIAN_PRACINHAS';
UPDATE ArtDefine_UnitInfos SET Formation = 'UnFormed' WHERE Type = 'ART_DEF_UNIT_U_BRAZILIAN_PRACINHAS';
-- MARINE
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_MARINE%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_MARINE%';
UPDATE ArtDefine_UnitInfos SET Formation = 'UnFormed' WHERE Type LIKE 'ART_DEF_UNIT_MARINE%';
-- LONGSWORDSMAN
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_LONGSWORDSMAN%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_LONGSWORDSMAN%';
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultMelee' WHERE Type LIKE 'ART_DEF_UNIT_LONGSWORDSMAN%';
-- DANISH BERSERKER
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.19 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_DANISH_BERSERKER';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_DANISH_BERSERKER';
UPDATE ArtDefine_UnitInfos SET Formation = 'UnFormed' WHERE Type = 'ART_DEF_UNIT_U_DANISH_BERSERKER';
-- JAPANESE SAMURAI
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_JAPANESE_SAMURAI';
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType = 'ART_DEF_UNIT_U_JAPANESE_SAMURAI';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_U_JAPANESE_SAMURAI','ART_DEF_UNIT_MEMBER_U_JAPANESE_SAMURAI',"3");
UPDATE ArtDefine_UnitInfos SET Formation = 'Samurai' WHERE Type = 'ART_DEF_UNIT_U_JAPANESE_SAMURAI';
-- PARATROOPER
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_PARATROOPER%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_PARATROOPER%';
UPDATE ArtDefine_UnitInfos SET Formation = 'UnFormed' WHERE Type LIKE 'ART_DEF_UNIT_PARATROOPER%';
-- RIFLEMAN
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_RIFLEMAN%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_RIFLEMAN%';
UPDATE ArtDefine_UnitInfos SET Formation = 'HonorableGunpowder' WHERE Type LIKE 'ART_DEF_UNIT_RIFLEMAN%';
-- DANISH SKI INFANTRY
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.17 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_DANISH_SKY_INFANTRY';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_DANISH_SKY_INFANTRY';
UPDATE ArtDefine_UnitInfos SET Formation = 'HonorableGunpowder' WHERE Type = 'ART_DEF_UNIT_U_DANISH_SKI_INFANTRY';
-- ETHIOPIA MEHAL SEFARI
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.17 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_ETHIOPIA_MEHAL_SEFARI';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_ETHIOPIA_MEHAL_SEFARI';
UPDATE ArtDefine_UnitInfos SET Formation = 'HonorableGunpowder' WHERE Type = 'ART_DEF_UNIT_U_ETHIOPIA_MEHAL_SEFARI';
-- SWEDISH CAROLEAN
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_SWEDISH_CAROLEAN';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_SWEDISH_CAROLEAN';
UPDATE ArtDefine_UnitInfos SET Formation = 'HonorableGunpowder' WHERE Type = 'ART_DEF_UNIT_U_SWEDISH_CAROLEAN';
-- CONFEDERATE RIFLEMAN CORPS/DIVISION
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_CONFEDERATE_RIFLEMAN%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitInfoType LIKE 'ART_DEF_UNIT_MEMBER_CONFEDERATE_RIFLEMAN%';
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType = 'ART_DEF_UNIT_CONFEDERATE_CORPS';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_CONFEDERATE_CORPS','ART_DEF_UNIT_MEMBER_CONFEDERATE_RIFLEMAN',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_CONFEDERATE_CORPS','ART_DEF_UNIT_MEMBER_CONFEDERATE_RIFLEMAN_V1',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_CONFEDERATE_CORPS','ART_DEF_UNIT_MEMBER_CONFEDERATE_RIFLEMAN_V2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType = 'ART_DEF_UNIT_CONFEDERATE_DIVISION';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_CONFEDERATE_DIVISION','ART_DEF_UNIT_MEMBER_CONFEDERATE_RIFLEMAN',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_CONFEDERATE_DIVISION','ART_DEF_UNIT_MEMBER_CONFEDERATE_RIFLEMAN_V2',"1");
UPDATE ArtDefine_UnitInfos SET Formation = 'HonorableGunpowder' WHERE Type = 'ART_DEF_UNIT_CONFEDERATE_CORPS';
UPDATE ArtDefine_UnitInfos SET Formation = 'HonorableGunpowder' WHERE Type = 'ART_DEF_UNIT_CONFEDERATE_DIVISION';
-- UNION RIFLEMAN CORPS/DIVISION
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_UNION_RIFLEMAN%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitInfoType = 'ART_DEF_UNIT_MEMBER_UNION_CORPS';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitInfoType = 'ART_DEF_UNIT_MEMBER_UNION_DIVISION';
UPDATE ArtDefine_UnitInfos SET Formation = 'HonorableGunpowder' WHERE Type = 'ART_DEF_UNIT_UNION_CORPS';
UPDATE ArtDefine_UnitInfos SET Formation = 'HonorableGunpowder' WHERE Type = 'ART_DEF_UNIT_UNION_DIVISION';
-- SCRAMBLE FORCE PUBLIQUE
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_SCRAMBLE_FORCE_PUBLIQUE';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_SCRAMBLE_FORCE_PUBLIQUE';
UPDATE ArtDefine_UnitInfos SET Formation = 'UnFormed' WHERE Type = 'ART_DEF_UNIT_SCRAMBLE_FORCE_PUBLIQUE';
-- SCRAMBLE FOREIGN VOLUNTEERS
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_SCRAMBLE_FOREIGN_VOLUNTEERS';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_SCRAMBLE_FOREIGN_VOLUNTEERS';
UPDATE ArtDefine_UnitInfos SET Formation = 'HonorableGunpowder' WHERE Type = 'ART_DEF_UNIT_SCRAMBLE_FOREIGN_VOLUNTEERS';
-- SCOUT
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_SCOUT%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_SCOUT%';
UPDATE ArtDefine_UnitInfos SET Formation = 'Scout' WHERE Type LIKE 'ART_DEF_UNIT_SCOUT%';
-- SHOSHONE PATHFINDER
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_SHOSHONE_PATHFINDER';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_SHOSHONE_PATHFINDER';
UPDATE ArtDefine_UnitInfos SET Formation = 'Scout' WHERE Type = 'ART_DEF_UNIT_U_SHOSHONE_PATHFINDER';
-- XCOM SQUAD
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_XCOM_SQUAD%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_XCOM_SQUAD%';
UPDATE ArtDefine_UnitInfos SET Formation = 'EarlyGreatArtist' WHERE Type LIKE 'ART_DEF_UNIT_XCOM_SQUAD%';
-- HAND AXE BARBARIAN (UNITCLASS_CHARIOT_ARCHER)
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_HAND_AXE_BARBARIAN';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_HAND_AXE_BARBARIAN';
UPDATE ArtDefine_UnitInfos SET Formation = 'Archer' WHERE Type = 'ART_DEF_UNIT_HAND_AXE_BARBARIAN';
-- SAXON HUSCARL
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_SAXON_HUSCARL';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_SAXON_HUSCARL';
UPDATE ArtDefine_UnitInfos SET Formation = 'FighterWing' WHERE Type = 'ART_DEF_UNIT_U_SAXON_HUSCARL';
-- SUMERIAN PHALANX
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.19 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_SUMERIAN_PHALANX';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_SUMERIAN_PHALANX';
UPDATE ArtDefine_UnitInfos SET Formation = 'Phalanx' WHERE Type = 'ART_DEF_UNIT_U_SUMERIAN_PHALANX';


-- CIVILIANS (0.18)
------------------------------------------------
-- ARCHAEOLOGIST
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_ARCHAEOLOGIST%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_ARCHAEOLOGIST%';
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType = 'ART_DEF_UNIT_ARCHAEOLOGIST';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_ARCHAEOLOGIST','ART_DEF_UNIT_MEMBER_ARCHAEOLOGIST',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_ARCHAEOLOGIST','ART_DEF_UNIT_MEMBER_ARCHAEOLOGIST_F1',"1");
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultCavalry' WHERE Type LIKE 'ART_DEF_UNIT_ARCHAEOLOGIST%';
-- EXPLORER
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_GREAT_EXPLORER%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_GREAT_EXPLORER%';
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType = 'ART_DEF_UNIT_GREAT_EXPLORER';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_EXPLORER','ART_DEF_UNIT_MEMBER_GREAT_EXPLORER',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_EXPLORER','ART_DEF_UNIT_MEMBER_GREAT_EXPLORER_F1',"1");
UPDATE ArtDefine_UnitInfos SET Formation = 'EarlyGreatArtist' WHERE Type LIKE 'ART_DEF_UNIT_EXPLORER%';
-- INQUISITOR
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_INQUISITOR%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_INQUISITOR%';
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType = 'ART_DEF_UNIT_INQUISITOR';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_INQUISITOR','ART_DEF_UNIT_MEMBER_INQUISITOR',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_INQUISITOR','ART_DEF_UNIT_MEMBER_INQUISITOR_01',"1");
UPDATE ArtDefine_UnitInfos SET Formation = 'EarlyGreatArtist' WHERE Type LIKE 'ART_DEF_UNIT_INQUISITOR%';
-- MILITARY ENGINEER
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_MILITARY_ENGINEER%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_MILITARY_ENGINEER%';
UPDATE ArtDefine_UnitInfos SET Formation = 'UnFormed' WHERE Type LIKE 'ART_DEF_UNIT_MILITARY_ENGINEER%';
-- MISSIONARY
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_MISSIONARY%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_MISSIONARY%';
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType = 'ART_DEF_UNIT_MISSIONARY';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_MISSIONARY','ART_DEF_UNIT_MEMBER_MISSIONARY',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_MISSIONARY','ART_DEF_UNIT_MEMBER_MISSIONARY_01',"1");
UPDATE ArtDefine_UnitInfos SET Formation = 'EarlyGreatArtist' WHERE Type LIKE 'ART_DEF_UNIT_MISSIONARY%';
-- SETTLER
--see Alternate Settlers for R.E.D.
-- SETTLER AFRICAN
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_AFRI%';
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.15 WHERE Type = 'ART_DEF_UNIT_MEMBER_AFRICAMEL';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_AFRI%';
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_AFRI';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_AFRI','ART_DEF_UNIT_MEMBER_AFRIMALE1',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_AFRI','ART_DEF_UNIT_MEMBER_AFRICAMEL',"1");
-- SETTLER MIDDLE EASTERN
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_MIDEAST';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_MIDEAST','ART_DEF_UNIT_MEMBER_AFRIMALE2',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_MIDEAST','ART_DEF_UNIT_MEMBER_AFRICAMEL',"1");
-- SETTLER AMERINDIAN
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_AMER%';
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.16 WHERE Type = 'ART_DEF_UNIT_MEMBER_AMERLLAMA';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_AMER%';
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_AMER';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_AMER','ART_DEF_UNIT_MEMBER_AMERMALE2',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_AMER','ART_DEF_UNIT_MEMBER_AMERLLAMA',"1");
-- SETTLER SOUTH AMERINDIAN
--UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_SOUTHAM%';
--UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_SOUTHAM%';
-- SETTLER ASIAN
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_F_';
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_M_';
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.14 WHERE Type = 'ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_OX';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN%';
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_ASIA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_ASIA','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_M1',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_ASIA','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_OX',"1");
-- SETTLER EURO
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_EURO%';
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.16 WHERE Type = 'ART_DEF_UNIT_MEMBER_EURODONKEY';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_EURO%';
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER','ART_DEF_UNIT_MEMBER_EUROMALE35',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER','ART_DEF_UNIT_MEMBER_EURODONKEY',"1");
-- SETTLER MEDITERRANEAN
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_MED';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_MED','ART_DEF_UNIT_MEMBER_EUROMALE35',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_MED','ART_DEF_UNIT_MEMBER_EURODONKEY',"1");
-- for R.E.D.
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_EURO';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_EURO','ART_DEF_UNIT_MEMBER_EUROMALE20',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_EURO','ART_DEF_UNIT_MEMBER_EURODONKEY',"1");
--UPDATE ArtDefine_UnitInfos SET Formation = 'LooseCivilian' WHERE Type LIKE 'ART_DEF_UNIT__SETTLER%';
UPDATE ArtDefine_UnitInfos SET Formation = 'EarlyGreatArtist' WHERE Type LIKE 'ART_DEF_UNIT__SETTLER%';

-- SPANISH TREASURE CART
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.063 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_SPANISH_TREASURE_CART';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_SPANISH_TREASURE_CART';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type = 'ART_DEF_UNIT_U_SPANISH_TREASURE_CART';
-- WORKER
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_WORKER_%';
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_WORKER_EURO_LATE';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_WORKER%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_WORKER_EURO_LATE';
--UPDATE ArtDefine_UnitInfos SET Formation = 'LooseCivilian' WHERE Type LIKE 'ART_DEF_UNIT__WORKER%';
UPDATE ArtDefine_UnitInfos SET Formation = 'EarlyGreatArtist' WHERE Type LIKE 'ART_DEF_UNIT__WORKER%';
--UPDATE ArtDefine_UnitInfos SET Formation = 'LooseCivilian' WHERE Type = 'ART_DEF_UNIT__WORKER_LATE';
UPDATE ArtDefine_UnitInfos SET Formation = 'EarlyGreatArtist' WHERE Type = 'ART_DEF_UNIT__WORKER_LATE';


-- GUNNERS (0.14)
------------------------------------------------
-- BAZOOKA INFANTRY
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_BAZOOKA_INFANTRY%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_BAZOOKA_INFANTRY%';
UPDATE ArtDefine_UnitInfos SET Formation = 'ThreeBigGuns' WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_BAZOOKA_INFANTRY%';
-- GATLING GUN
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.14 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_GATLINGGUN%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_GATLINGGUN%';
UPDATE ArtDefine_UnitInfos SET Formation = 'ThreeBigGuns' WHERE Type LIKE 'ART_DEF_UNIT_GATLINGGUN%';
-- MACHINE GUN
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.14 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_MACHINEGUN%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_MACHINEGUN%';
UPDATE ArtDefine_UnitInfos SET Formation = 'ThreeBigGuns' WHERE Type LIKE 'ART_DEF_UNIT_MACHINEGUN%';


-- GREAT PEOPLE
------------------------------------------------
-- GREAT ARTIST
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_ARTIST%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_ARTIST%';
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType = 'ART_DEF_UNIT_ARTIST';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_ARTIST','ART_DEF_UNIT_MEMBER_GREATARTIST_EARLY_FLUTE',1);
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_ARTIST','ART_DEF_UNIT_MEMBER_GREATARTIST_EARLY_FLAGBEARER',"1");
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type = 'ART_DEF_UNIT_MEMBER_GREATARTIST_LATE'; --vehicle

-- GREAT ARTIST (BNW)
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_GREAT_ARTIST%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_GREAT_ARTIST%';
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType = 'ART_DEF_UNIT_GREAT_ARTIST';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_GREAT_ARTIST','ART_DEF_UNIT_MEMBER_GREAT_ARTIST',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_GREAT_ARTIST','ART_DEF_UNIT_MEMBER_GREAT_ARTIST_F1',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType = 'ART_DEF_UNIT_GREAT_ARTIST_POSTMODERN';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_GREAT_ARTIST_POSTMODERN','ART_DEF_UNIT_MEMBER_GREAT_ARTIST_LATE',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_GREAT_ARTIST_POSTMODERN','ART_DEF_UNIT_MEMBER_GREAT_ARTIST_LATE_F1',"1");
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultCavalry' WHERE Type LIKE 'ART_DEF_UNIT_GREAT_ARTIST%';

-- GREAT MUSICIAN
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_GREAT_MUSICIAN%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_GREAT_MUSICIAN%';
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType = 'ART_DEF_UNIT_GREAT_MUSICIAN';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_GREAT_MUSICIAN','ART_DEF_UNIT_MEMBER_GREAT_MUSICIAN',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_GREAT_MUSICIAN','ART_DEF_UNIT_MEMBER_GREAT_MUSICIAN_F1',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType = 'ART_DEF_UNIT_GREAT_MUSICIAN_POSTMODERN';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_GREAT_MUSICIAN_POSTMODERN','ART_DEF_UNIT_MEMBER_GREAT_MUSICIAN_LATE',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_GREAT_MUSICIAN_POSTMODERN','ART_DEF_UNIT_MEMBER_GREAT_MUSICIAN_LATE_F1',"1");
UPDATE ArtDefine_UnitInfos SET Formation = 'EarlyGreatArtist' WHERE Type LIKE 'ART_DEF_UNIT_GREAT_MUSICIAN%';

-- GREAT WRITER
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_GREAT_WRITER%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_GREAT_WRITER%';
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType = 'ART_DEF_UNIT_GREAT_WRITER';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_GREAT_WRITER','ART_DEF_UNIT_MEMBER_GREAT_WRITER',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_GREAT_WRITER','ART_DEF_UNIT_MEMBER_GREAT_WRITER_F1',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType = 'ART_DEF_UNIT_GREAT_WRITER_POSTMODERN';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_GREAT_WRITER_POSTMODERN','ART_DEF_UNIT_MEMBER_GREAT_WRITER_LATE',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_GREAT_WRITER_POSTMODERN','ART_DEF_UNIT_MEMBER_GREAT_WRITER_LATE_F1',"1");
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultCavalry' WHERE Type LIKE 'ART_DEF_UNIT_GREAT_WRITER%';

-- GREAT PROPHET
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_GREAT_PROPHET%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_GREAT_PROPHET%';
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType = 'ART_DEF_UNIT_GREAT_PROPHET';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_GREAT_PROPHET','ART_DEF_UNIT_MEMBER_GREAT_PROPHET',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_GREAT_PROPHET','ART_DEF_UNIT_MEMBER_GREAT_PROPHET_MALE',"1");
UPDATE ArtDefine_UnitInfos SET Formation = 'EarlyGreatArtist' WHERE Type LIKE 'ART_DEF_UNIT_GREAT_PROPHET%';


-- MOUNTED GREAT PEOPLE
------------------------------------------------
-- GREAT GENERAL
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_GREATGENERAL%';
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type = 'ART_DEF_UNIT_MEMBER_GREATGENERAL_LATE';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_GREATGENERAL%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_GREATGENERAL_LATE';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type LIKE 'ART_DEF_UNIT_GENERAL%';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type = 'ART_DEF_UNIT_GENERAL_LATE';
-- CONFEDERATE GREAT GENERAL
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.15 WHERE Type = 'ART_DEF_UNIT_MEMBER_CONFEDERATE_GREAT_GENERAL';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_CONFEDERATE_GREAT_GENERAL';
UPDATE ArtDefine_UnitInfos SET Formation = 'UnFormed' WHERE Type = 'ART_DEF_UNIT_CONFEDERATE_GENERAL';
-- MOGOLIAN GREAT GENERAL
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.15 WHERE Type = 'ART_DEF_UNIT_MEMBER_GREATGENERAL_KHAN';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_GREATGENERAL_KHAN';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type = 'ART_DEF_UNIT_GENERAL_KHAN';
-- UNION GREAT GENERAL
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.15 WHERE Type = 'ART_DEF_UNIT_MEMBER_UNION_GREAT_GENERAL';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_UNION_GREAT_GENERAL';
UPDATE ArtDefine_UnitInfos SET Formation = 'UnFormed' WHERE Type = 'ART_DEF_UNIT_UNION_GENERAL';

-- GREAT MERCHANT
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_GREATMERCHANT%';
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.11 WHERE Type = 'ART_DEF_UNIT_MEMBER_GREATMERCHANT_LATE';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_GREATMERCHANT%';
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType = 'ART_DEF_UNIT_MERCHANT';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_MERCHANT','ART_DEF_UNIT_MEMBER_GREATMERCHANT_EARLY_LEADER',"1");
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_GREATMERCHANT_LATE';
UPDATE ArtDefine_UnitInfos SET Formation = 'EarlyGreatMerchant' WHERE Type LIKE 'ART_DEF_UNIT_MERCHANT%';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type = 'ART_DEF_UNIT_MERCHANT_LATE';
-- VENETIAN MERCHANT
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.18 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_VENETIAN_MERCHANT';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_VENETIAN_MERCHANT';
UPDATE ArtDefine_UnitInfos SET Formation = 'EarlyGreatMerchant' WHERE Type = 'ART_DEF_UNIT_U_VENETIAN_MERCHANT';

-- GREAT PEOPLE VEHICLES
------------------------------------------------
-- GREAT ENGINEER
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_GREATENGINEER%';
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.09 WHERE Type = 'ART_DEF_UNIT_MEMBER_GREATENGINEER_LATE';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_GREATENGINEER%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_GREATENGINEER_LATE';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type LIKE 'ART_DEF_UNIT_ENGINEER%';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type = 'ART_DEF_UNIT_ENGINEER_LATE';
-- GREAT SCIENTIST
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_GREATSCIENTIST%';
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type = 'ART_DEF_UNIT_MEMBER_GREATSCIENTIST_LATE';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_GREATSCIENTIST%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_GREATSCIENTIST_LATE';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type LIKE 'ART_DEF_UNIT_SCIENTIST%';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type = 'ART_DEF_UNIT_SCIENTIST_LATE';


-- MOUNTED (0.15)
------------------------------------------------
-- CARAVAN
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.15 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_CARAVAN%';
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.04 WHERE Type = 'ART_DEF_UNIT_MEMBER_CARAVAN_LATE';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_CARAVAN%';
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType = 'ART_DEF_UNIT_CARAVAN';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_CARAVAN','ART_DEF_UNIT_MEMBER_CARAVAN',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType = 'ART_DEF_UNIT_CARAVAN_POSTMODERN';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_CARAVAN_POSTMODERN','ART_DEF_UNIT_MEMBER_CARAVAN_LATE',"1");
UPDATE ArtDefine_UnitInfos SET Formation = 'ThreeInLine' WHERE Type LIKE 'ART_DEF_UNIT_CARAVAN%';
UPDATE ArtDefine_UnitInfos SET Formation = 'TheeInLineStag' WHERE Type = 'ART_DEF_UNIT_CARAVAN_POSTMODERN';

-- CAVALRY
--note R.E.D. French and German cavalry use UNIT_MEMBER_LANCER_%
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.15 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_CAVALRY%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_CAVALRY%';
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultCavalry' WHERE Type LIKE 'ART_DEF_UNIT_CAVALRY%';
-- AUSTRIAN HUSSAR
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.15 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_AUSTRIAN_HUSSAR';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_AUSTRIAN_HUSSAR';
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultCavalry' WHERE Type = 'ART_DEF_UNIT_U_AUSTRIAN_HUSSAR';
-- MORROCAN BERBER CAVALRY
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.15 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_MORROCAN_BERBER_CAVALRY';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_MORROCAN_BERBER_CAVALRY';
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultCavalry' WHERE Type = 'ART_DEF_UNIT_U_MORROCAN_BERBER_CAVALRY';
-- RUSSIAN COSSACK
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.15 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_RUSSIAN_COSSACK';
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.15 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_RUSSIAN_COSSACK_V2';			
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.15 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_RUSSIAN_COSSACK_V3';
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType = 'ART_DEF_UNIT_U_RUSSIAN_COSSACK';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_U_RUSSIAN_COSSACK','ART_DEF_UNIT_MEMBER_U_RUSSIAN_COSSACK',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_U_RUSSIAN_COSSACK','ART_DEF_UNIT_MEMBER_U_RUSSIAN_COSSACK_V2',"1");
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_U_RUSSIAN_COSSACK','ART_DEF_UNIT_MEMBER_U_RUSSIAN_COSSACK_V3',"1");
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultCavalry' WHERE Type = 'ART_DEF_UNIT_U_RUSSIAN_COSSACK';
-- SHOSHONE COMANCHE RIDERS
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.15 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_SHOSHONE_COMANCHE_RIDERS';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_SHOSHONE_COMANCHE_RIDERS';
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultCavalry' WHERE Type = 'ART_DEF_UNIT_U_SHOSHONE_COMANCHE_RIDERS';
-- CONFEDERATE CAVALRY CARBINE/PISTOL
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.15 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_CONFEDERATE_CAVALRY%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_CONFEDERATE_CAVALRY%';
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultCavalry' WHERE Type LIKE 'ART_DEF_UNIT_CONFEDERATE_CAVALRY%';
-- UNION CAVALRY CARBINE/PISTOL
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_UNION_CAVALRY%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_UNION_CAVALRY%';
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultCavalry' WHERE Type LIKE 'ART_DEF_UNIT_UNION_CAVALRY%';


-- HORSEMAN
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.15 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_HORSEMAN%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_HORSEMAN%';
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultCavalry' WHERE Type LIKE 'ART_DEF_UNIT_HORSEMAN%';
-- BARBARIAN HORSEMAN
-- BYZANTIUM CATAPHRACT
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.15 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_BYZANTIUM_CATAPHRACT';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_BYZANTIUM_CATAPHRACT';
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultCavalry' WHERE Type = 'ART_DEF_UNIT_U_BYZANTIUM_CATAPHRACT';
-- CARTHAGE AFRICANFOREST ELEPHANT
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.13 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_CARTHAGE_AFRICANFOREST_ELEPHANT';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_CARTHAGE_AFRICANFOREST_ELEPHANT';
UPDATE ArtDefine_UnitInfos SET Formation = 'ChariotElephant' WHERE Type = 'ART_DEF_UNIT_U_CARTHAGE_AFRICANFOREST_ELEPHANT';
-- GREEK COMPANION CAVALRY
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.15 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_GREEK_COMPANIONCAVALRY';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_GREEK_COMPANIONCAVALRY';
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultCavalry' WHERE Type = 'ART_DEF_UNIT_U_GREEK_COMPANIONCAVALRY';

-- KNIGHT
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.15 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_KNIGHT%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_KNIGHT%';
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultCavalry' WHERE Type LIKE 'ART_DEF_UNIT_KNIGHT%';
-- ARABIAN CAMEL ARCHER
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.15 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_ARABIAN_CAMELARCHER';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_ARABIAN_CAMELARCHER';
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultCavalry' WHERE Type = 'ART_DEF_UNIT_U_ARABIAN_CAMELARCHER';
-- MONGOLIAN KESHIK
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.15 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_MONGOLIAN_KESHIK';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_MONGOLIAN_KESHIK';
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultCavalry' WHERE Type = 'ART_DEF_UNIT_U_MONGOLIAN_KESHIK';
-- SIAMESE WAR ELEPHANT
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_SIAMESE_WARELEPHANT';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_SIAMESE_WARELEPHANT';
UPDATE ArtDefine_UnitInfos SET Formation = 'ChariotElephant' WHERE Type = 'ART_DEF_UNIT_U_SIAMESE_WARELEPHANT';
-- SONGHAI MUSLIM CAVALRY			
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.15 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_SONGHAI_MUSLIMCAVALRY';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_SONGHAI_MUSLIMCAVALRY';
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultCavalry' WHERE Type = 'ART_DEF_UNIT_U_SONGHAI_MUSLIMCAVALRY';
-- SPANISH CONQUISTADOR			
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.16 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_SPANISH_CONQUISTADOR';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_SPANISH_CONQUISTADOR';
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultCavalry' WHERE Type = 'ART_DEF_UNIT_U_SPANISH_CONQUISTADOR';

-- LANCER
--note R.E.D. French, German, and Hun cavalry use UNIT_MEMBER_LANCER_%
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.14 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_LANCER%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_LANCER%';
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultCavalry' WHERE Type LIKE 'ART_DEF_UNIT_LANCER%';
--OTTOMAN SIPAHI
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.15 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_OTTOMAN_SIPAHI';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_OTTOMAN_SIPAHI';
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultCavalry' WHERE Type = 'ART_DEF_UNIT_U_OTTOMAN_SIPAHI';
-- POLISH WINGED HUSSAR
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.15 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_POLISH_WINGED_HUSSAR';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_POLISH_WINGED_HUSSAR';
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultCavalry' WHERE Type = 'ART_DEF_UNIT_U_POLISH_WINGED_HUSSAR';
-- SWEDISH HAKKAPELITTA
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.16 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_SWEDISH_HAKKAPELITTA';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_SWEDISH_HAKKAPELITTA';
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultCavalry' WHERE Type = 'ART_DEF_UNIT_U_SWEDISH_HAKKAPELITTA';


-- GIANT DEATH ROBOT (0.12)
------------------------------------------------
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_MECH%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_MECH%';
UPDATE ArtDefine_UnitInfos SET Formation = 'Vehicle' WHERE Type LIKE 'ART_DEF_UNIT_MECH%';


-- HORSE-DRAWN VEHICLES (0.13)
------------------------------------------------
-- CHARIOT ARCHER
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.13 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_CHARIOTARCHER%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_CHARIOTARCHER%';
UPDATE ArtDefine_UnitInfos SET Formation = 'ChariotElephant' WHERE Type LIKE 'ART_DEF_UNIT_CHARIOT_ARCHER%';
-- EGYPTIAN WAR CHARIOT
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.13 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_EGYPTIAN_WARCHARIOT';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_EGYPTIAN_WARCHARIOT';
UPDATE ArtDefine_UnitInfos SET Formation = 'ChariotElephant' WHERE Type = 'ART_DEF_UNIT_U_EGYPTIAN_WARCHARIOT';
-- HITTITE WAR CHARIOT
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.145 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_HITTITE_WARCHARIOT';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_HITTITE_WARCHARIOT';
UPDATE ArtDefine_UnitInfos SET Formation = 'ChariotElephant' WHERE Type = 'ART_DEF_UNIT_U_HITTITE_WARCHARIOT';
-- HUNS HORSE ARCHER
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.15 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_HUNS_HORSE_ARCHER';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_HUNS_HORSE_ARCHER';
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultCavalry' WHERE Type = 'ART_DEF_UNIT_U_HUNS_HORSE_ARCHER';
-- INDIAN WAR ELEPHANT
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_INDIAN_WARELEPHANT';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_INDIAN_WARELEPHANT';
UPDATE ArtDefine_UnitInfos SET Formation = 'ChariotElephant' WHERE Type = 'ART_DEF_UNIT_U_INDIAN_WARELEPHANT';


-- VEHICLES
------------------------------------------------
-- MECHANIZED INFANTRY
--not updated by R.E.D., but counters change from MECH% wildcard above
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.1 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_MECHANIZEDINFANTRY%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_MECHANIZEDINFANTRY%';
UPDATE ArtDefine_UnitInfos SET Formation = 'Vehicle' WHERE Type LIKE 'ART_DEF_UNIT_MECHANIZED_INFANTRY%';
-- MODERN ARMOR
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.1 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_MODERNARMOR%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_MODERNARMOR%';
UPDATE ArtDefine_UnitInfos SET Formation = 'Vehicle' WHERE Type LIKE 'ART_DEF_UNIT_MODERN_ARMOR%';
-- SMOKEY LANDSHIP LEVEL 1 (UNITCLASS_LAND_IRONCLAD)
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.16 WHERE Type = 'ART_DEF_UNIT_MEMBER_SMOKEY_LANDSHIP_LEVEL_1';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_SMOKEY_LANDSHIP_LEVEL_1';
UPDATE ArtDefine_UnitInfos SET Formation = 'TwoBigGuns' WHERE Type = 'ART_DEF_UNIT_SMOKEY_LANDSHIP_LEVEL_1';
-- SMOKEY LANDSHIP LEVEL 2 (UNITCLASS_LANDSHIP)
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.15 WHERE Type = 'ART_DEF_UNIT_MEMBER_SMOKEY_LANDSHIP_LEVEL_2';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_SMOKEY_LANDSHIP_LEVEL_2';
UPDATE ArtDefine_UnitInfos SET Formation = 'TwoBigGuns' WHERE Type = 'ART_DEF_UNIT_SMOKEY_LANDSHIP_LEVEL_2';
-- SMOKEY LANDSHIP LEVEL 3 (UNITCLASS_LAND_LEVIATHAN)
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.20 WHERE Type = 'ART_DEF_UNIT_MEMBER_SMOKEY_LANDSHIP_LEVEL_3';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_SMOKEY_LANDSHIP_LEVEL_3';
UPDATE ArtDefine_UnitInfos SET Formation = 'TwoBigGuns' WHERE Type = 'ART_DEF_UNIT_SMOKEY_LANDSHIP_LEVEL_3';
-- TANK
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_TANK%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_TANK%';
UPDATE ArtDefine_UnitInfos SET Formation = 'Vehicle' WHERE Type LIKE 'ART_DEF_UNIT_TANK%';
-- GERMAN PANZER
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.11 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_GERMAN_PANZER';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_GERMAN_PANZER';
UPDATE ArtDefine_UnitInfos SET Formation = 'Vehicle' WHERE Type = 'ART_DEF_UNIT_U_GERMAN_PANZER';
-- WW1 TANK
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.11 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_WW1_TANK%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_WW1_TANK%';
UPDATE ArtDefine_UnitInfos SET Formation = 'TwoBigGuns' WHERE Type LIKE 'ART_DEF_UNIT_WW1_TANK%';


-- HELICOPTER GUNSHIP (0.1)
------------------------------------------------
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.1 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_HELICOPTERGUNSHIP%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_HELICOPTERGUNSHIP%';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type LIKE 'ART_DEF_UNIT_HELICOPTER_GUNSHIP%';


-- SPACESHIP PARTS (0.1)
------------------------------------------------
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.1 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_SS_%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_SS_%';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type LIKE 'ART_DEF_UNIT_SS_%';


-- SIEGE
------------------------------------------------
-- ARTILLERY
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_ARTILLERY%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_ARTILLERY%';
UPDATE ArtDefine_UnitInfos SET Formation = 'TwoBigGuns' WHERE Type LIKE 'ART_DEF_UNIT_ARTILLERY%';
-- ANTI-AIRCRAFT GUN
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_ANTIAIRCRAFTGUN%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_ANTIAIRCRAFTGUN%';
UPDATE ArtDefine_UnitInfos SET Formation = 'TwoBigGuns' WHERE Type LIKE 'ART_DEF_UNIT_ANTI_AIRCRAFT_GUN%';
-- ANTI-TANK GUN
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_ANTITANKGUN%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_ANTITANKGUN%';
UPDATE ArtDefine_UnitInfos SET Formation = 'TwoBigGuns' WHERE Type LIKE 'ART_DEF_UNIT_ANTI_TANK_GUN%';
-- CANNON
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_CANNON%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_CANNON%';
UPDATE ArtDefine_UnitInfos SET Formation = 'TwoBigGuns' WHERE Type LIKE 'ART_DEF_UNIT_CANNON%';
-- CONFEDERATE ARTILLERY NAPOLEON (UNITCLASS_CANNON) / PARROTT (UNITCLASS_RIFLED_CANNON)
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_CONFEDERATE_ARTILLERY%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_CONFEDERATE_ARTILLERY%';
UPDATE ArtDefine_UnitInfos SET Formation = 'TwoBigGuns' WHERE Type LIKE 'ART_DEF_UNIT_CONFEDERATE_ARTILLERY%';
-- UNION ARTILLERY NAPOLEON (UNITCLASS_CANNON) / PARROTT (UNITCLASS_RIFLED_CANNON)
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_UNION_ARTILLERY%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_UNION_ARTILLERY%';
UPDATE ArtDefine_UnitInfos SET Formation = 'TwoBigGuns' WHERE Type LIKE 'ART_DEF_UNIT_UNION_ARTILLERY%';
-- CATAPULT
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_CATAPULT%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_CATAPULT%';
UPDATE ArtDefine_UnitInfos SET Formation = 'TwoBigGuns' WHERE Type LIKE 'ART_DEF_UNIT_CATAPULT%';
-- ASSYRIAN SIEGE TOWER
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.1 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_ASSYRIAN_SIEGE_TOWER';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_ASSYRIAN_SIEGE_TOWER';
UPDATE ArtDefine_UnitInfos SET Formation = 'TwoBigGuns' WHERE Type = 'ART_DEF_UNIT_U_ASSYRIAN_SIEGE_TOWER';
-- ROMAN BALLISTA
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_ROMAN_BALLISTA';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_ROMAN_BALLISTA';
UPDATE ArtDefine_UnitInfos SET Formation = 'TwoBigGuns' WHERE Type = 'ART_DEF_UNIT_U_ROMAN_BALLISTA';
-- HUN BATTERING RAM (UNITCLASS_SPEARMAN)
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.115 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_HUNS_BATTERING_RAM';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_HUNS_BATTERING_RAM';
UPDATE ArtDefine_UnitInfos SET Formation = 'TwoBigGuns' WHERE Type = 'ART_DEF_UNIT_U_HUNS_BATTERING_RAM';
-- MOBILE SAM
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.11 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_MOBILESAM%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_MOBILESAM%';
UPDATE ArtDefine_UnitInfos SET Formation = 'Vehicle' WHERE Type LIKE 'ART_DEF_UNIT_MOBILE_SAM%';
-- ROCKET ARTILLERY
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.09 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_ROCKETARTILLERY%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_ROCKETARTILLERY%';
UPDATE ArtDefine_UnitInfos SET Formation = 'TwoBigGuns' WHERE Type LIKE 'ART_DEF_UNIT_ROCKET_ARTILLERY%';
-- TREBUCHET
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_TREBUCHET%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_TREBUCHET%';
UPDATE ArtDefine_UnitInfos SET Formation = 'TwoBigGuns' WHERE Type LIKE 'ART_DEF_UNIT_TREBUCHET%';
-- KOREAN HWACHA
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.13 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_KOREAN_HWACHA';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_KOREAN_HWACHA';
UPDATE ArtDefine_UnitInfos SET Formation = 'TwoBigGuns' WHERE Type = 'ART_DEF_UNIT_U_KOREAN_HWACHA';



-- SHIPS
------------------------------------------------
-- CARAVEL
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.14 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_CARAVEL%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_CARAVEL%';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type LIKE 'ART_DEF_UNIT_CARAVEL%';
-- KOREAN TURTLESHIP
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.14 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_KOREAN_TURTLESHIP';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_KOREAN_TURTLESHIP';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type = 'ART_DEF_UNIT_U_KOREAN_TURTLESHIP';
--PORTUGUESE NAU?
-- GALLEASS
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.14 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_GALLEASS%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_GALLEASS%';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type LIKE 'ART_DEF_UNIT_GALLEASS%';
-- VENETIAN GALLEASS
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.14 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_VENETIAN_GALLEASS';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_VENETIAN_GALLEASS';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type = 'ART_DEF_UNIT_U_VENETIAN_GALLEASS';
-- PRIVATEER (G+K)
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.14 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_XP_PRIVATEER%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_XP_PRIVATEER%';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type LIKE 'ART_DEF_UNIT_XP_PRIVATEER%';
-- PRIVATEER
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.14 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_PRIVATEER%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_PRIVATEER%';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type LIKE 'ART_DEF_UNIT_PRIVATEER%';
-- DUTCH SEA BEGGAR
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.14 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_DUTCH_SEA_BEGGARS';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_DUTCH_SEA_BEGGARS';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type = 'ART_DEF_UNIT_U_DUTCH_SEA_BEGGARS';
-- PORTUGUESE CARRACK
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.14 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_PORTUGUESE_CARRACK';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_PORTUGUESE_CARRACK';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type = 'ART_DEF_UNIT_U_PORTUGUESE_CARRACK';
-- CONFEDERATE IRONCLAD
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type = 'ART_DEF_UNIT_MEMBER_CONFEDERATE_IRONCLAD';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_CONFEDERATE_IRONCLAD';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type = 'ART_DEF_UNIT_CONFEDERATE_IRONCLAD';
-- UNION IRONCLAD
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type = 'ART_DEF_UNIT_MEMBER_UNION_IRONCLAD';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_UNION_IRONCLAD';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type = 'ART_DEF_UNIT_UNION_IRONCLAD';

-- BARBARIAN GALLEY
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.09 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_BARBARIAN_GALLEY%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_BARBARIAN_GALLEY';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type LIKE 'ART_DEF_UNIT_BARBARIAN_GALLEY%';
-- BATTLESHIP				
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.09 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_BATTLESHIP%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_BATTLESHIP%';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type LIKE 'ART_DEF_UNIT_BATTLESHIP%';
-- CARRIER
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.09 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_CARRIER%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_CARRIER%';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type LIKE 'ART_DEF_UNIT_CARRIER%';
-- DESTROYER
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_DESTROYER%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_DESTROYER%';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type LIKE 'ART_DEF_UNIT_DESTROYER%';
-- FRIGATE
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.14 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_FRIGATE%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_FRIGATE%';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type LIKE 'ART_DEF_UNIT_FRIGATE%';
-- ENGLISH SHIP OF THE LINE
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.14 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_ENGLISH_SHIPOFTHELINE';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_ENGLISH_SHIPOFTHELINE';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type = 'ART_DEF_UNIT_U_ENGLISH_SHIPOFTHELINE';
-- IRONCLAD
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_IRONCLAD%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_IRONCLAD%';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type LIKE 'ART_DEF_UNIT_IRONCLAD%';
-- MISSILE CRUISER
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.11 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_MISSILECRUISER%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_MISSILECRUISER%';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type LIKE 'ART_DEF_UNIT_MISSILE_CRUISER%';
-- NUCLEAR SUBMARINE
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.1 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_NUCLEARSUBMARINE%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_NUCLEARSUBMARINE%';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type LIKE 'ART_DEF_UNIT_NUCLEAR_SUBMARINE%';
-- SUBMARINE
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.16 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_SUBMARINE%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_SUBMARINE%';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type LIKE 'ART_DEF_UNIT_SUBMARINE%';
-- TRIREME
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.07 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_TRIREME%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_TRIREME%';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type LIKE 'ART_DEF_UNIT_TRIREME%';
-- BYZANTIUM DROMON
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.16 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_BYZANTIUM_DROMON';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_BYZANTIUM_DROMON';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type = 'ART_DEF_UNIT_U_BYZANTIUM_DROMON';
-- CARTHAGE QUINQUEREME
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.075 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_CARTHAGE_QUINQUEREME';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_CARTHAGE_QUINQUEREME';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type = 'ART_DEF_UNIT_U_CARTHAGE_QUINQUEREME';


-- CIVILIAN SHIPS
------------------------------------------------
-- CARGO SHIP
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.16 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_CARGO_SHIP%';
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.14 WHERE Type = 'ART_DEF_UNIT_MEMBER_CARGO_SHIP_MID';
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.08 WHERE Type = 'ART_DEF_UNIT_MEMBER_CARGO_SHIP_LATE';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_CARGO_SHIP%';
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultCavalry' WHERE Type LIKE 'ART_DEF_UNIT_CARGO_SHIP%';
-- GREAT ADMIRAL
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_GREAT_ADMIRAL%';
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type = 'ART_DEF_UNIT_MEMBER_GREAT_ADMIRAL_LATE';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_GREAT_ADMIRAL%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_GREAT_ADMIRAL_LATE';
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultCavalry' WHERE Type LIKE 'ART_DEF_UNIT_GREAT_ADMIRAL%';
UPDATE ArtDefine_UnitInfos SET Formation = 'DefaultCavalry' WHERE Type = 'ART_DEF_UNIT_GREAT_ADMIRAL_LATE';
-- WORKBOAT
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.07 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_WORKBOAT%';
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.07 WHERE Type = 'ART_DEF_UNIT_MEMBER_WORKBOAT_INDUSTRIAL';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_WORKBOAT%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_WORKBOAT_INDUSTRIAL';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type LIKE 'ART_DEF_UNIT_WORKBOAT%';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type = 'ART_DEF_UNIT_WORKBOAT_LATE';



-- PLANES
------------------------------------------------
-- ATOMIC BOMB
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.07 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_ATOMICBOMB%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_ATOMICBOMB%';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type LIKE 'ART_DEF_UNIT_ATOMIC_BOMB%';
-- BOMBER				
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.08 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_BOMBER%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_BOMBER%';
UPDATE ArtDefine_UnitInfos SET Formation = 'BomberWing' WHERE Type LIKE 'ART_DEF_UNIT_BOMBER%';
-- AMERICAN B-17
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.08 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_AMERICAN_B17';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_AMERICAN_B17';
UPDATE ArtDefine_UnitInfos SET Formation = 'BomberWing' WHERE Type = 'ART_DEF_UNIT_U_AMERICAN_B17';
-- FIGHTER
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.08 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_FIGHTER%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_FIGHTER%';
UPDATE ArtDefine_UnitInfos SET Formation = 'FighterWing' WHERE Type LIKE 'ART_DEF_UNIT_FIGHTER%';
-- JAPANESE ZERO
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.07 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_JAPANESE_ZERO';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_JAPANESE_ZERO';
UPDATE ArtDefine_UnitInfos SET Formation = 'FighterWing' WHERE Type = 'ART_DEF_UNIT_U_JAPANESE_ZERO';
-- JETFIGHTER
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.09 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_JETFIGHTER%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_JETFIGHTER%';
UPDATE ArtDefine_UnitInfos SET Formation = 'FighterWing' WHERE Type LIKE 'ART_DEF_UNIT_JET_FIGHTER%';
-- SMOKEY AIRSHIP LEVEL 1 (NITCLASS_AIRSHIP)
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.21 WHERE Type = 'ART_DEF_UNIT_MEMBER_SMOKEY_AIRSHIP_LEVEL_1';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_SMOKEY_AIRSHIP_LEVEL_1';
UPDATE ArtDefine_UnitInfos SET Formation = 'FighterWing' WHERE Type = 'ART_DEF_UNIT_SMOKEY_STEAM_AIRSHIP_LEVEL_1';
-- SMOKEY BLIMP (UNITCLASS_SKY_FORTRESS)
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.21 WHERE Type = 'ART_DEF_UNIT_MEMBER_SMOKEY_BLIMP';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_SMOKEY_BLIMP';
UPDATE ArtDefine_UnitInfos SET Formation = 'FighterWing' WHERE Type = 'ART_DEF_UNIT_SMOKEY_STEAM_AIRSHIP';
-- SMOKEY STEAM FIGHTER (UNITCLASS_FLYER)
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.09 WHERE Type = 'ART_DEF_UNIT_MEMBER_SMOKEY_STEAM_FIGHTER';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_SMOKEY_STEAM_FIGHTER';
UPDATE ArtDefine_UnitInfos SET Formation = 'FighterWing' WHERE Type = 'ART_DEF_UNIT_SMOKEY_STEAM_FIGHTER';
-- STEALTH BOMBER
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.08 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_STEALTHBOMBER%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_STEALTHBOMBER%';
UPDATE ArtDefine_UnitInfos SET Formation = 'BomberWing' WHERE Type LIKE 'ART_DEF_UNIT_STEALTH_BOMBER%';
-- WW1 BOMBER
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.08 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_WW1_BOMBER%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_WW1_BOMBER%';
UPDATE ArtDefine_UnitInfos SET Formation = 'BomberWing' WHERE Type LIKE 'ART_DEF_UNIT_WW1_BOMBER%';
-- WW1 FIGHTER
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.09 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_WW1_FIGHTER%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 3 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_WW1_FIGHTER%';
UPDATE ArtDefine_UnitInfos SET Formation = 'FighterWing' WHERE Type LIKE 'ART_DEF_UNIT_WW1_FIGHTER%';


-- BALLISTICS
------------------------------------------------
-- GUIDED MISSILE
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.14 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_GUIDEDMISSILE%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_GUIDEDMISSILE%';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type LIKE 'ART_DEF_UNIT_GUIDED_MISSILE%';
-- NUCLEAR MISSILE
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.14 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_NUCLEARMISSILE%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 1 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_NUCLEARMISSILE%';
UPDATE ArtDefine_UnitInfos SET Formation = '' WHERE Type LIKE 'ART_DEF_UNIT_NUCLEAR_MISSILE%';


-- EMBARKED UNITS
------------------------------------------------
-- GALLEON
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.12 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_GALLEON%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_GALLEON%';
UPDATE ArtDefine_UnitInfos SET Formation = 'TwoBigGuns' WHERE Type LIKE 'ART_DEF_UNIT_GALLEON%';
-- SPANISH GALLEON
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.15 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_SPANISH_GALLEON';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_SPANISH_GALLEON';
UPDATE ArtDefine_UnitInfos SET Formation = 'TwoBigGuns' WHERE Type = 'ART_DEF_UNIT_U_SPANISH_GALLEON';
-- GALLEY
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.14 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_GALLEY%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_GALLEY%';
UPDATE ArtDefine_UnitInfos SET Formation = 'TwoBigGuns' WHERE Type LIKE 'ART_DEF_UNIT_GALLEY%';
-- DANISH LONGBOAT
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.10 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_DANISH_LONGBOAT';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_DANISH_LONGBOAT';
UPDATE ArtDefine_UnitInfos SET Formation = 'TwoBigGuns' WHERE Type = 'ART_DEF_UNIT_U_DANISH_LONGBOAT';
-- POLYNESIAN WAR CANOE
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.07 WHERE Type = 'ART_DEF_UNIT_MEMBER_U_POLYNESIAN_WAR_CANOE';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType = 'ART_DEF_UNIT_MEMBER_U_POLYNESIAN_WAR_CANOE';
UPDATE ArtDefine_UnitInfos SET Formation = 'TwoBigGuns' WHERE Type = 'ART_DEF_UNIT_U_POLYNESIAN_WAR_CANOE';
-- TRANSPORT
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.11 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_TRANSPORT%';
UPDATE ArtDefine_UnitInfoMemberInfos SET NumMembers = 2 WHERE UnitMemberInfoType LIKE 'ART_DEF_UNIT_MEMBER_TRANSPORT%';
UPDATE ArtDefine_UnitInfos SET Formation = 'TwoBigGuns' WHERE Type LIKE 'ART_DEF_UNIT_TRANSPORT%';